import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import {Providers} from './providers';

import Navbarhead from "@/components/Navbar/Navbarhead";
import { SessionProvider } from "next-auth/react";

import { auth } from  "../auth"; // 引用您在 auth.ts 中導出的 auth 函數，並重新命名以避免潛在衝突

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout=async({children}: {children: React.ReactNode}) =>{
  const session = await auth(); // 獲取當前用戶的會話信息
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
      <SessionProvider session={session}>
        {/*wrapped the children between ThemeProvider to make sure the theme aplly ot all pages*/}
        <div className="flex flex-col min-h-screen bg-neutral-900 relative">
            {/* hero ui provider */}
            <Providers>
              <main className="flex-grow relative z-20 overflow-hidden">
                
                <Navbarhead/>
                {children}
              </main>
            </Providers>
        </div>
      </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;
